### PR TITLE
fix:typo import objc_property

### PR DESCRIPTION
**Pull request by pome-ta**
I am thrilled every time I use it and I love it. Thank you!

 There were parts of the tutorial in the documentation that I felt were unnecessary.

 This is the first time I have sent a PR. I would appreciate it if you could let me know if there are any other procedures I need to follow.

https://github.com/beeware/rubicon-objc/blob/643532d87b54d01f461ef022d1523029fe92a64e/docs/tutorial/tutorial-2.rst?plain=1#L85

Import brackets were deemed unnecessary and removed.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Thanks for the kind words, and the fix!

As for procedures around contributing - the only thing you'll be missing is a change note. We automatically generate our release notes from files committed as part of each PR; in this case, you need to add a file named `changes/530.misc.rst` that describes the change - something like `A typo in the tutorial was corrected.`.

**Comment by qqfunc** [comment]
See [this guide](https://toga.readthedocs.io/en/stable/how-to/contribute/code.html#add-change-information-for-release-notes) for help.

**Comment by pome-ta** [comment]
@freakboy3742 
Thank you for the specific explanation.
I had missed an important procedure.

Also, thank you for your quick response.

(I don't have much knowledge, so when I pushed the file, I was surprised that CI started running 😂)

**Comment by pome-ta** [comment]
@qqfunc 

Thank you for always supporting me by providing information on my oversights 😍

**Review by freakboy3742 — APPROVED** [review]
Looks good - thanks for the fix!

**Pull request merged**
